package com.wangle.happysing.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wangle.happysing.db.SingInfoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig singInfoBeanDaoConfig;

    private final SingInfoBeanDao singInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        singInfoBeanDaoConfig = daoConfigMap.get(SingInfoBeanDao.class).clone();
        singInfoBeanDaoConfig.initIdentityScope(type);

        singInfoBeanDao = new SingInfoBeanDao(singInfoBeanDaoConfig, this);

        registerDao(SingInfoBean.class, singInfoBeanDao);
    }
    
    public void clear() {
        singInfoBeanDaoConfig.clearIdentityScope();
    }

    public SingInfoBeanDao getSingInfoBeanDao() {
        return singInfoBeanDao;
    }

}
